import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';

// Soft C-major bell arpeggio (C5 → E5 → G5 → C6).
// Generated by scripts/genSound.js — replace the WAV to change the sound.
const player = createAudioPlayer(require('../../assets/sounds/complete.wav'));
let configured = false;

export async function playCompletionSound() {
  try {
    if (!configured) {
      configured = true;
      await setAudioModeAsync({ playsInSilentMode: true });
    }
    await player.seekTo(0);
    player.play();
  } catch (e) {
    console.warn('completion sound failed', e);
  }
}
